---
- hosts: webserver
  remote_user: root
  become: yes
  tasks:
   - name: install httpd
     yum: name=httpd state=installed
   - name: copy index.html file
     copy: src=index.html dest=/var/www/html
     notify: restart httpd
   - name: start httpd
     service: name=httpd state=started
  handlers:
   - name: restart httpd
     service: name=httpd state=restarted 
