---
- hosts: webserver
  remote_user: root
  become: yes
  vars_files:
    - abc.yml
  tasks:
    - name: install httpd
      yum: name={{pkg}} state=installed
    - name: copy index.html file
      copy: src=index.html dest=/var/www/html
    - name: start httpd
      service: name={{pkg}} state=started

