---
- hosts: webserver
  remote_user: root
  become: yes
  tasks:
   - name: install httpd
     yum: name=httpd state=installed
     tags:
      - install
   - name: copy index.html file
     copy: src=index.html dest=/var/www/html
     tags:
      - configure
   - name: start httpd
     service: name=httpd state=started
     tags:
      - service
